### ISSUE TITLE
grant access permission

### ISSUE THREAD

**Issue by PilgrimVR** [ComputerElite/QuestAppVersionSwitcher#71]
Im on quest 3 and this grant access permission thing is stopping me from doing anything. I cant get past this stage.

**Comment by ComputerElite** [comment]
Would you mind describing your issue more depth, providing what QAVS is saying and perhaps share a screenshot or recording of your problem.

**Comment by PilgrimVR** [comment]
![808056dce7a08d0aacf84b3672a100eb](https://github.com/user-attachments/assets/82dc9fef-88bc-4eca-9e20-d28517045ef6)
I do not know what to do. This puts me into a tutorial that when i complete it, it says that it was invalid

**Comment by PilgrimVR** [comment]
It says "wireless port" and idk what to do.

**Comment by ComputerElite** [comment]
You need to enter the wireless port which is in the wireless debugging menu. It's the number after the :

**Comment by ntnoriginal** [comment]
The only issue I'm having is going back from the android setting tab once I have access to the port key and code, since there isn't away to get back to the access screen without closing the app switcher altogether. But since the window opens up on the same screen as the app switcher there isn't a way to type in the code without clicking off of the pair code screen without it saying "failed to pair" which results in the code resetting. so regardless there isn't a way to type in the same code as the one given before closing the app to type it in. in the screenshot of the tutorial given for the grant access page the device in the picture says pixel 6 meaning it wasn't done in the quest alone. a video demo would be appreciated .

**Comment by ComputerElite** [comment]
That specific issue is known and will be fixed in an upcoming release. So far I haven't found a way to open the settings window in a new tab. You can however install an app launcher or use SideQuest on your pc to launch the settings in a new window

**Comment by ComputerElite** [comment]
It has been successfully done on multiple quests during testing. The person screenshotting just didn't have one of the screenshots I needed and during development I just had my phone with me

**Comment by ntnoriginal** [comment]
thanks for the tip ill try on my pc

**Comment by PilgrimVR** [comment]
Also to open your settings on quest, try an app on sidequest called lightning launcher. I used that to type the code in.

**Comment by PilgrimVR** [comment]
The only thing i request is that you make a detailed demo video on how to make this app work.

**Comment by ComputerElite** [comment]
I just got a quest 3 to try stuff with. The open settings button does seem to open a new window provided you previously moved the qavs window one spot to the left

**Comment by ComputerElite** [comment]
nevermind, this doesn't seem to be consistent

**Comment by ComputerElite** [comment]
Just released 1.16.6 which should fix most of the issues. lmk if it works for you if you want to test. A video will be made in the following days

**Comment by PilgrimVR** [comment]
Thank you.
